-- 001_extensions_and_enums.sql
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE user_role_enum AS ENUM ('SUPER_ADMIN','ADMIN','MODERATOR','CAPTAIN','PLAYER');
CREATE TYPE season_status_enum AS ENUM ('UPCOMING','ACTIVE','COMPLETED','ARCHIVED');
CREATE TYPE league_status_enum AS ENUM ('UPCOMING','ACTIVE','COMPLETED');
CREATE TYPE fixture_status_enum AS ENUM ('SCHEDULED','COMPLETED','POSTPONED','CANCELLED','FORFEITED');
CREATE TYPE match_source_enum AS ENUM ('AUTO','MANUAL','FORFEIT');
CREATE TYPE match_status_enum AS ENUM ('PENDING_REVIEW','APPROVED','REJECTED');
CREATE TYPE transfer_status_enum AS ENUM ('PENDING_PLAYER','PENDING_ADMIN','APPROVED','REJECTED','CANCELLED','KICKED');
CREATE TYPE notification_type_enum AS ENUM (
  'TRANSFER_OFFER','TRANSFER_ACCEPTED','TRANSFER_REJECTED','TRANSFER_ADMIN_APPROVED',
  'TRANSFER_KICKED','MATCH_APPROVED','MATCH_REJECTED','COMMENT_REPLY','POST_LIKED',
  'TEAM_ASSIGNMENT','SYSTEM_MESSAGE'
);
CREATE TYPE report_status_enum AS ENUM ('PENDING','REVIEWED','DISMISSED','ACTION_TAKEN');
CREATE TYPE sync_status_enum AS ENUM ('RUNNING','COMPLETED','FAILED','PARTIAL');
