-- ==============================================================================
-- Migration: 20261003233000_admin_panel_audit_only.sql
-- Description: Restricts audit_logs strictly to administrative panel actions.
-- 1. Drops all 12 database audit triggers that wrote raw table mutations.
-- 2. Drops the internal audit_log_action() trigger function.
-- 3. Performs a controlled one-time cleanup of legacy DB trigger records
--    (identifiable by: action IN ('INSERT', 'UPDATE', 'DELETE') AND description IS NULL).
-- 4. Preserves application-level audit logging and RLS append-only rules.
-- ==============================================================================

-- 1. Drop all database-level audit triggers on the 12 tables
DROP TRIGGER IF EXISTS trg_audit_matches ON public.matches;
DROP TRIGGER IF EXISTS trg_audit_transfers ON public.transfers;
DROP TRIGGER IF EXISTS trg_audit_team_memberships ON public.team_memberships;
DROP TRIGGER IF EXISTS trg_audit_seasons ON public.seasons;
DROP TRIGGER IF EXISTS trg_audit_leagues ON public.leagues;
DROP TRIGGER IF EXISTS trg_audit_teams ON public.teams;
DROP TRIGGER IF EXISTS trg_audit_fixtures ON public.fixtures;
DROP TRIGGER IF EXISTS trg_audit_posts ON public.posts;
DROP TRIGGER IF EXISTS trg_audit_comments ON public.comments;
DROP TRIGGER IF EXISTS trg_audit_team_penalties ON public.team_penalties;
DROP TRIGGER IF EXISTS trg_audit_player_legacy_career_stats ON public.player_legacy_career_stats;
DROP TRIGGER IF EXISTS trg_audit_profiles ON public.profiles;

-- 2. Drop the trigger function
DROP FUNCTION IF EXISTS public.audit_log_action();

-- 3. One-time controlled cleanup of legacy DB trigger records.
-- Application audit records generated by logAdminAudit() ALWAYS have
-- a non-null semantic description and entity_label, and use semantic actions
-- (e.g. CREATE_TEAM, UPDATE_MATCH_SCORE). Therefore, they are 100% safe from deletion.
DELETE FROM public.audit_logs
WHERE action IN ('INSERT', 'UPDATE', 'DELETE')
  AND description IS NULL;

-- 4. Verify RLS remains enabled and append-only
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
